name: md changed

on:
  push:
    paths:
      - '**.md'

jobs:
  handle-md-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.19'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1
        with:
          since_last_remote_commit: true
          include_all_old_new_renamed_files: true
          files: raw/**/*.md

      - name: Added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file added"
            file_name=$(basename $file '.md')
            base_path=$(dirname $file)
            bash scripts/compile-page.sh $base_path $file_name

            if [[ $base_path == raw/posts* ]]; then
              echo "adding $file_name to index"
              bash scripts/add-post-to-index.sh $file_name
            fi
          done

      - name: Modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file modified"
            file_name=$(basename $file '.md')
            base_path=$(dirname $file)
            bash scripts/compile-page.sh $base_path $file_name
          done

      - name: Deleted files
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            echo "$file deleted"
            file_name=$(basename $file '.md')
            base_path=$(dirname $file)
            bash scripts/delete-page.sh $base_path $file_name

            if [[ $base_path == raw/posts* ]]; then
              echo "removing $file_name from index"
              bash scripts/rm-post-from-index.sh $file_name
            fi
          done

      - name: Renamed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_old_new_renamed_files }}; do
            from="$(echo $file | cut -d',' -f1)"
            echo "remove old page $from"
            ofile_name=$(basename $from '.md')
            obase_path=$(dirname $from)
            bash scripts/delete-page.sh $obase_path $ofile_name

            if [[ $obase_path == raw/posts* ]]; then
              echo "removing $ofile_name from index"
              l=$(grep -Fn $ofile_name raw/index.md | cut -d':' -f1)
              d=$(sed -n "${l}p" raw/index.md | cut -d'|' -f2)
              bash scripts/rm-post-from-index.sh $ofile_name
            fi

            to="$(echo $file | cut -d',' -f2)"
            echo "add new page $to"
            nfile_name=$(basename $to '.md')
            nbase_path=$(dirname $to)
            bash scripts/compile-page.sh $nbase_path $nfile_name

            if [[ $nbase_path == raw/posts* ]]; then
              echo "adding $nfile_name to index"
              bash scripts/add-post-to-index.sh $nfile_name ${l=3} ${d=$(date +"%a %b %d %Y")}
            fi
          done

      - name: Compile index
        run: bash scripts/compile-page.sh raw index

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'updating html pages'
