name: md changed

on:
  push:
    branches:
      - main
    paths:
      - 'raw/**/*.md'

jobs:
  handle-md-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.19'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1
        with:
          since_last_remote_commit: true
          files: raw/**/*.md

      - name: Compile pages
        run: ./handle_changes "${{ steps.changed-files.outputs.added_files }}" "${{ steps.changed-files.outputs.modified_files }}" "${{ steps.changed-files.outputs.deleted_files }}"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'updating html pages'
