name: md changed

on:
  push:
    paths:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1
        with:
          since_last_remote_commit: true
          include_all_old_new_renamed_files: true
          files: raw/**/*.md

      - name: Added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            sh scripts/compile-page.sh $file
          done

      - name: Modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            sh scripts/compile-page.sh $file
          done

      - name: Deleted files
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            sh scripts/delete-page.sh $file
          done

      - name: Renamed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_old_new_renamed_files }}; do
            from="$(echo $file | cut -d',' -f1)"
            to="$(echo $file | cut -d',' -f2)"

            echo "from $from"
            echo "to $to"
          done
