name: md changed

on:
  push:
    paths:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26.1

      - run: |
          for i in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $i
          done
